# Generated by Django 2.1.7 on 2019-02-27 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marcas',
            new_name='Marca',
        ),
    ]
