# Generated by Django 2.1.7 on 2019-03-04 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20190227_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_clave', models.CharField(max_length=50)),
                ('modelo_nombre', models.CharField(max_length=50)),
                ('modelo_descripcion', models.TextField(max_length=1000)),
                ('marca_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Marca')),
            ],
        ),
    ]
