# Generated by Django 2.1.7 on 2019-03-04 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_modelo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelo',
            old_name='marca_id',
            new_name='marca',
        ),
    ]
